export const UPDATE_SCENE = 'UPDATE_SCENE';
export const UPDATE_GAME_SONG_ID = 'UPDATE_GAME_SONG_ID';
export const UPDATE_PLAYING_MODE = 'UPDATE_PLAYING_MODE';

export const UPDATE_SONGS_PENDING = 'UPDATE_SONGS_PENDING';
export const UPDATE_SONGS_SUCCESS = 'UPDATE_SONGS_SUCCESS';
export const UPDATE_SONGS_FAILURE = 'UPDATE_SONGS_FAILURE';

export const INCREASE_CURRENT_SONG_INDEX = 'INCREASE_CURRENT_SONG_INDEX';
export const DECREASE_CURRENT_SONG_INDEX = 'DECREASE_CURRENT_SONG_INDEX';

export const MUSIC_COLLECTION = 'MUSIC_COLLECTION';
export const GAME = 'GAME';
export const RESULT = 'RESULT';
export const LOBBY = 'LOBBY';

export const UPDATE_MISS = 'UPDATE_MISS';
export const UPDATE_STATS = 'UPDATE_STATS';

export const UPDATE_RANKING_PENDING = 'UPDATE_RANKING_PENDING';
export const UPDATE_RANKING_SUCCESS = 'UPDATE_RANKING_SUCCESS';
export const UPDATE_RANKING_FAILURE = 'UPDATE_RANKING_FAILURE';
