export const UPDATE_SCENE = 'UPDATE_SCENE';
export const UPDATE_CURRENT_SONG_ID = 'UPDATE_CURRENT_SONG_ID';

export const UPDATE_SONGS_PENDING = 'UPDATE_SONGS_PENDING';
export const UPDATE_SONGS_SUCCESS = 'UPDATE_SONGS_SUCCESS';
export const UPDATE_SONGS_FAILURE = 'UPDATE_SONGS_FAILURE';

export const FETCH_SONG_PENDING = 'FETCH_SONG_PENDING';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';
export const FETCH_SONG_FAILURE = 'FETCH_SONG_FAILURE';

export const MUSIC_COLLECTION = 'MUSIC_COLLECTION';
export const GAME = 'GAME';
export const RESULT = 'RESULT';
export const LOBBY = 'LOBBY';